import express from 'express';
const router = express.Router();
require('dotenv').config();
import authController from '../controllers/authController';
import addCardToInventoryValidationController from '../controllers/addCardToInventoryValidationController';
import addCardToInventoryController from '../controllers/addCardToInventoryController';
import finishSaleValidationController from '../controllers/finishSaleValidationController';
import finishSaleController from '../controllers/finishSaleController';
import allSalesController from '../controllers/allSalesController';
import getSalesByTitleController from '../controllers/getSalesByTitleController';
import receiveCardsValidationController from '../controllers/receiveCardsValidationController';
import receiveCardsController from '../controllers/receiveCardsController';
import getSuspendedSalesController from '../controllers/getSuspendedSalesController';
import suspendedSaleByIdController from '../controllers/suspendedSaleByIdController';
import createSuspendedSaleController from '../controllers/createSuspendedSaleController';
import deleteSuspendedSaleController from '../controllers/deleteSuspendedSaleController';
import getCardsByFilterController from '../controllers/getCardsByFilterController';
import distinctSetNamesController from '../controllers/distinctSetNamesController';
import getCardsWithInfoController from '../controllers/getCardsWithInfoController';
import getReceivedCardsController from '../controllers/getReceivedCardsController';
import getReceivedCardsByIdController from '../controllers/getReceivedCardsByIdController';
import salesReportController from '../controllers/salesReportController';
import bulkSearchController from '../controllers/bulkSearchController';

router.use(authController);
router.post('/addCardToInventory', addCardToInventoryValidationController);
router.post('/addCardToInventory', addCardToInventoryController);
router.post('/finishSale', finishSaleValidationController);
router.post('/finishSale', finishSaleController);
router.get('/allSales', allSalesController);
router.get('/getSaleByTitle', getSalesByTitleController);
router.post('/receiveCards', receiveCardsValidationController);
router.post('/receiveCards', receiveCardsController);
router.get('/suspendSale', getSuspendedSalesController);
router.get('/suspendSale/:id', suspendedSaleByIdController);
router.post('/suspendSale', createSuspendedSaleController);
router.delete('/suspendSale/:id', deleteSuspendedSaleController);
router.get('/getCardsByFilter', getCardsByFilterController);
router.get('/getDistinctSetNames', distinctSetNamesController);
router.get('/getCardsWithInfo', getCardsWithInfoController);
router.get('/getReceivedCards', getReceivedCardsController);
router.get('/getReceivedCards/:id', getReceivedCardsByIdController);
router.get('/getSalesReport', salesReportController);
router.get('/bulkSearch', bulkSearchController);

export default router;
